# Generated by Django 2.2.6 on 2019-10-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='definition',
            new_name='input',
        ),
        migrations.AddField(
            model_name='task',
            name='output',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
