# Generated by Django 2.2.6 on 2019-10-29 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_auto_20191029_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Passed', 'OK'), ('Wrong answer', 'WA'), ('Memory limit exceeded', 'MLE'), ('Runtime error', 'RE'), ('Time limit exceeded', 'TLE'), ('Compilation error', 'CE'), ('Internal system error', 'IE')], default='Internal system error', max_length=12)),
                ('sourceCode', models.TextField()),
                ('language', models.CharField(choices=[('C', 'C'), ('C++', 'CPP'), ('GO', 'GO'), ('Python', 'PYTHON'), ('Java', 'JAVA')], max_length=8)),
                ('createdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('error', models.TextField(null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
